In [1]:
# importing relevant library
import numpy as np

In [55]:
class Node:

  def __init__(self, arr):
    self.arr = arr
    self.parent = None
    self.h = 0
    self.g = 0
    self.f = 0
  
  # function for comparing equality between two nodes
  def __eq__(self, otherNode):
    return np.array_equiv(self.arr, otherNode.arr)

In [42]:
def generate_child(arr):
  
  n = arr.shape[0]
  temp = np.where(arr == 0)
  i = temp[0][0]
  j = temp[1][0]

  child = []

  if i-1 >= 0:
    temp = arr.copy()
    temp[i-1][j] = arr[i][j]
    temp[i][j] = arr[i-1][j]
    child.append(Node(temp))
  
  
  if j-1 >= 0:
    temp = arr.copy()
    temp[i][j-1] = arr[i][j]
    temp[i][j] = arr[i][j-1]
    child.append(Node(temp))
    

  if i+1 < n:
    temp = arr.copy()
    temp[i+1][j] = arr[i][j]
    temp[i][j] = arr[i+1][j]
    child.append(Node(temp))
    

  if j+1 < n:
    temp = arr.copy()
    temp[i][j+1] = arr[i][j]
    temp[i][j] = arr[i][j+1]
    child.append(Node(temp))
  
  
  return child

In [61]:
ar = np.array([[1, 2, 3], [0, 5, 4], [7, 6, 8]])

goal = np.array([[0, 1, 2], [3, 4, 5], [6, 7, 8]])

# ar = np.array([[0, 2], [3, 1]])
# goal = np.array([[0, 1], [2, 3]])

print(ar, goal)
start = Node(ar)
goal = Node(goal)

# br = np.array([[1, 2, 3], [5, 0, 4], [7, 6, 8]])
# [a.arr for a in generate_child(br)]

[[1 2 3]
 [0 5 4]
 [7 6 8]] [[0 1 2]
 [3 4 5]
 [6 7 8]]


In [43]:
def bfs(start):
  queue = []
  queue.append(start)

  visited = []

  while len(queue):
    current = queue[0]
    visited.append(current)
    queue.pop(0)

    if current == goal:
      print(current.arr)
      break

    children = generate_child(current.arr)

    for child in children:
      if child not in visited:
        queue.append(child)

    print(current.arr)

bfs(start)

[[0 2]
 [3 1]]
[[3 2]
 [0 1]]
[[2 0]
 [3 1]]
[[3 2]
 [1 0]]
[[2 1]
 [3 0]]
[[3 0]
 [1 2]]
[[2 1]
 [0 3]]
[[0 3]
 [1 2]]
[[0 1]
 [2 3]]


In [44]:
def dfs(start):
  stack = []
  stack.append(start)

  visited = []

  while len(stack):
    current = stack[-1]
    visited.append(current)
    stack.pop(-1)

    if current == goal:
      print(current.arr)
      break

    children = generate_child(current.arr)

    for child in children:
      if child not in visited:
        stack.append(child)

    print(current.arr)

dfs(start)

[[0 2]
 [3 1]]
[[2 0]
 [3 1]]
[[2 1]
 [3 0]]
[[2 1]
 [0 3]]
[[0 1]
 [2 3]]


In [51]:
# function for calculating manhattan distance
def manhattan_distance(a, b):
  return abs(a[0] - b[0]) + abs(a[1] - b[1])

def distance(a, b):
  n = a.shape[0]
  first = []
  second = []

  for i in range(n*n):
    temp = np.where(a == i)
    first.append((temp[0][0], temp[1][0]))

  for i in range(n*n):
    temp = np.where(b == i)
    second.append((temp[0][0], temp[1][0]))

  total = 0

  for i in range(len(first)):
    total += manhattan_distance(first[i], second[i])

  return total

distance(start.arr, goal.arr)




4

In [52]:
# finding the node with minimum cost
def find_min_node(openList):
  currentIndex = 0
  currentNode = openList[0]

  for index, node in enumerate(openList):
    if node.f < currentNode.f:
      currentIndex = index
      currentNode = node

  return currentNode, currentIndex

In [ ]:
# function for finding the shortest path
def search(start, goal):

  # creating Open and closed Lists
  openList = []
  closedList = []

  # inserting the first node in the open list
  openList.append(start)

  # traversing the graph using A* algorithm
  while len(openList):

    # find the node with minimum cost
    currentNode, index = find_min_node(openList)
    openList.pop(index)

    # add currentNode in closed list
    closedList.append(currentNode)

    # if the goal node is reached then break
    if currentNode == goal:
      break
    
    # find all the children of current Node
    children = generate_child(currentNode.arr)

    # add the new child to the openList
    for child in children:

      if child in closedList:                             # if child already in closed list, do nothing
        continue

      if child in openList:                               # if child in openList then update cost
        child.g = min(child.g, currentNode.g + 1)
        child.h = distance(child.arr, goal.arr)
        child.f = child.g + child.h
        child.parent = currentNode
        continue
      
      child.h = distance(child.arr, goal.arr)    # calculating f = g + h
      child.f = child.g + child.h

      child.parent = currentNode                          # adding parent to the child

      openList.append(child)

      print(currentNode.arr, '\n')

  return closedList                                       # return closed list for finding the path

closedList = search(start, goal)
print(closedList[-1].arr)

In [70]:
# function to print the steps required to 
def print_path(start, closedList, goal):

  path = []

  # start with the goal node and backtrack to the starting node by visiting
  # parents of each backtracked node
  currentNode = closedList[-1]
  
  while currentNode != start:
    path.append(currentNode.arr)
    currentNode = currentNode.parent
  path.append(currentNode.arr)

  # print the path from start to end
  for p in path[::-1]:
    print(p, '\n')

print_path(start, closedList, goal)

[[1 2 3]
 [0 5 4]
 [7 6 8]] 

[[1 2 3]
 [5 0 4]
 [7 6 8]] 

[[1 2 3]
 [5 4 0]
 [7 6 8]] 

[[1 2 0]
 [5 4 3]
 [7 6 8]] 

[[1 0 2]
 [5 4 3]
 [7 6 8]] 

[[0 1 2]
 [5 4 3]
 [7 6 8]] 

[[5 1 2]
 [0 4 3]
 [7 6 8]] 

[[5 1 2]
 [4 0 3]
 [7 6 8]] 

[[5 1 2]
 [4 3 0]
 [7 6 8]] 

[[5 1 0]
 [4 3 2]
 [7 6 8]] 

[[5 0 1]
 [4 3 2]
 [7 6 8]] 

[[0 5 1]
 [4 3 2]
 [7 6 8]] 

[[4 5 1]
 [0 3 2]
 [7 6 8]] 

[[4 5 1]
 [3 0 2]
 [7 6 8]] 

[[4 0 1]
 [3 5 2]
 [7 6 8]] 

[[4 1 0]
 [3 5 2]
 [7 6 8]] 

[[4 1 2]
 [3 5 0]
 [7 6 8]] 

[[4 1 2]
 [3 0 5]
 [7 6 8]] 

[[4 1 2]
 [3 6 5]
 [7 0 8]] 

[[4 1 2]
 [3 6 5]
 [0 7 8]] 

[[4 1 2]
 [0 6 5]
 [3 7 8]] 

[[0 1 2]
 [4 6 5]
 [3 7 8]] 

[[1 0 2]
 [4 6 5]
 [3 7 8]] 

[[1 6 2]
 [4 0 5]
 [3 7 8]] 

[[1 6 2]
 [0 4 5]
 [3 7 8]] 

[[1 6 2]
 [3 4 5]
 [0 7 8]] 

[[1 6 2]
 [3 4 5]
 [7 0 8]] 

[[1 6 2]
 [3 0 5]
 [7 4 8]] 

[[1 0 2]
 [3 6 5]
 [7 4 8]] 

[[0 1 2]
 [3 6 5]
 [7 4 8]] 

[[3 1 2]
 [0 6 5]
 [7 4 8]] 

[[3 1 2]
 [6 0 5]
 [7 4 8]] 

[[3 1 2]
 [6 4 5]
 [7 0 8]] 

[[3 1 2]
 