In [ ]:
# importing relevant library
import numpy as np

In [ ]:
# creating maze
maze = np.zeros((8, 8))

# assigning 1 to places where the cell is blocked
for i in range(5):
  maze[3][2 + i] = 1

maze[4][0] = 1
maze[5][2] = 1
maze[5][6] = 1

print("Maze is:\n", maze)

Maze is:
 [[0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 1. 1. 1. 1. 0.]
 [1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]]


In [ ]:
# creating class for the node
class Node:

  def __init__(self, pos=(0, 0)):
    self.pos = pos
    self.parent = None
    self.f = self.g = self.h = 0
  
  # function for comparing equality between two nodes
  def __eq__(self, otherNode):
    return self.pos == otherNode.pos


In [ ]:
# defining heuristic function
def manhattan_distance(a, b):
  return abs(a[0] - b[0]) + abs(a[1] - b[1])

In [ ]:
# finding the node with minimum cost
def find_min_node(openList):
  currentIndex = 0
  currentNode = openList[0]

  for index, node in enumerate(openList):
    if node.f < currentNode.f:
      currentIndex = index
      currentNode = node

  return currentNode, currentIndex

In [ ]:
# find all the valid child nodes of a given node
def get_child_nodes(currentNode):
  x, y = currentNode.pos

  childNodes = []

  if x - 1 >= 0 and maze[x-1][y] != 1:
    childNodes.append(Node(pos = (x-1, y)))
  
  if y - 1 >= 0 and maze[x][y-1] != 1:
    childNodes.append(Node(pos = (x, y-1)))
  
  if x + 1 < 8 and maze[x+1][y] != 1:
    childNodes.append(Node(pos = (x+1, y)))
  
  if y + 1 < 8 and maze[x][y+1] != 1:
    childNodes.append(Node(pos = (x, y+1)))
  
  return childNodes

In [ ]:
# function for finding the shortest path
def search_path(start, end, maze):

  # creating Open and closed Lists
  openList = []
  closedList = []

  # inserting the first node in the open list
  openList.append(start)

  # traversing the graph using A* algorithm
  while len(openList):

    # find the node with minimum cost
    currentNode, index = find_min_node(openList)
    openList.pop(index)

    # add currentNode in closed list
    closedList.append(currentNode)

    # if the goal node is reached then break
    if currentNode == end:
      break
    
    # find all the children of current Node
    children = get_child_nodes(currentNode)

    # add the new child to the openList
    for child in children:

      if child in closedList:                             # if child already in closed list, do nothing
        continue

      if child in openList:                               # if child in openList then update cost
        child.g = min(child.g, currentNode.g + 1)
        child.h = manhattan_distance(child.pos, end.pos)
        child.f = child.g + child.h
        child.parent = currentNode
        continue
      
      child.h = manhattan_distance(child.pos, end.pos)    # calculating f = g + h
      child.f = child.g + child.h

      child.parent = currentNode                          # adding parent to the child

      openList.append(child)

  return closedList                                       # return closed list for finding the path

In [ ]:
# function to print path from source to goal node
def print_path(start, closedList, maze, end):
  newMaze = [['_' for _ in range(8)]]*8

  path = []

  # start with the goal node and backtrack to the starting node by visiting
  # parents of each backtracked node
  currentNode = closedList[-1]
  
  while currentNode != start:
    path.append(currentNode.pos)
    currentNode = currentNode.parent
  path.append(currentNode.pos)

  print('lenght of the path:', len(path) - 1, '\n')

  # creating the result maze
  for i in range(8):
    for j in range(8):
      if (i, j) in path:        # assign 'p' if the cell is part of the path
        newMaze[i][j] = 'p'
      elif maze[i][j] == 1:
        newMaze[i][j] = '#'     # assign '#' if the cell is blocked
      else:
        newMaze[i][j] = '_'     # assign '_' if cell is empty and not travelled

      if i == start.pos[0] and j == start.pos[1]:   # source cell
        newMaze[i][j] = 'S'
      elif i == end.pos[0] and j == end.pos[1]:     # destination cell
        newMaze[i][j] = 'G'

      print(newMaze[i][j], end='  ')   
    print()

In [ ]:
# take input for the start node
a = int(input('x coordinate of starting position: '))
b = int(input('y coordinate of the starting postion: '))

while maze[b][a]:
  print('This coordinate is blocked. Please try other coordinates')
  a = int(input('x coordinate of starting position: '))
  b = int(input('y coordinate of the starting postion: '))

# taking input for the goal node
c = int(input('x coordinate of goal position: '))
d = int(input('y coordinate of the goal postion: ')) 

while maze[d][c]:
  print('This coordinate is blocked. Please try other coordinates')
  c = int(input('x coordinate of goal position: '))
  d = int(input('y coordinate of the goal postion: ')) 

# initialize start and end
start = Node(pos = (b, a))
end = Node(pos = (d, c))

print("\nstarting position:", start.pos)
print('goal postion:', end.pos)

# find the list of all visited nodes
closedList = search_path(start, end, maze)

x coordinate of starting position: 2
y coordinate of the starting postion: 3
This coordinate is blocked. Please try other coordinates
x coordinate of starting position: 0
y coordinate of the starting postion: 0
x coordinate of goal position: 2
y coordinate of the goal postion: 3
This coordinate is blocked. Please try other coordinates
x coordinate of goal position: 7
y coordinate of the goal postion: 7

starting position: (0, 0)
goal postion: (7, 7)


In [ ]:
# printing results
print('A total of', len(closedList), 'nodes were explored for getting the correct path\n')
print_path(start, closedList, maze, end)

A total of 15 nodes were explored for getting the correct path

lenght of the path: 14 

S  _  _  _  _  _  _  _  
p  _  _  _  _  _  _  _  
p  _  _  _  _  _  _  _  
p  p  #  #  #  #  #  _  
#  p  _  _  _  _  _  _  
_  p  #  _  _  _  #  _  
_  p  _  _  _  _  _  _  
_  p  p  p  p  p  p  G  
